use clinicasj;

INSERT INTO `problemas` VALUES (1,'Dolor al calor');
INSERT INTO `problemas` VALUES (2,'Dolor al frio');
INSERT INTO `problemas` VALUES (3,'Dolor al masticar');
INSERT INTO `problemas` VALUES (4,'Sarro');
INSERT INTO `problemas` VALUES (5,'Mal aliento');
INSERT INTO `problemas` VALUES (6,'Sangrado de encias');
INSERT INTO `problemas` VALUES (7,'Impactacion de alimentos');
INSERT INTO `problemas` VALUES (8,'Fracturas de dientes');
INSERT INTO `problemas` VALUES (9,'Inflamacion');
INSERT INTO `problemas` VALUES (10,'Sensibilidad');
INSERT INTO `problemas` VALUES (11,'Cambio de color');
INSERT INTO `problemas` VALUES (12,'Faltan piezas');

INSERT INTO `sintomas` VALUES (1,'Anemia');
INSERT INTO `sintomas` VALUES (2,'Asma');
INSERT INTO `sintomas` VALUES (3,'Artritis');
INSERT INTO `sintomas` VALUES (4,'Cancer');
INSERT INTO `sintomas` VALUES (5,'Cuidados psiquiatrico');
INSERT INTO `sintomas` VALUES (6,'Colapso de valvula mitral');
INSERT INTO `sintomas` VALUES (7,'Diabetes');
INSERT INTO `sintomas` VALUES (8,'Dolor de cabeza');
INSERT INTO `sintomas` VALUES (9,'Dependencia de farmacos');
INSERT INTO `sintomas` VALUES (10,'Enfermedades venereas');
INSERT INTO `sintomas` VALUES (11,'Epilepsia');
INSERT INTO `sintomas` VALUES (12,'VIH positivo');
INSERT INTO `sintomas` VALUES (13,'Hemofilia');
INSERT INTO `sintomas` VALUES (14,'Habitos de fumar');
INSERT INTO `sintomas` VALUES (15,'Glaucoma');
INSERT INTO `sintomas` VALUES (16,'Problemas hepaticos');
INSERT INTO `sintomas` VALUES (17,'Problemas nerviosos');
INSERT INTO `sintomas` VALUES (18,'Problemas cardiacos');
INSERT INTO `sintomas` VALUES (19,'Problemas posturales');
INSERT INTO `sintomas` VALUES (20,'Problemas sanguinios');
INSERT INTO `sintomas` VALUES (21,'Problemas de tiroide');
INSERT INTO `sintomas` VALUES (22,'Picazon (rash, urticarias)');
INSERT INTO `sintomas` VALUES (23,'Presion sanguinea alta');
INSERT INTO `sintomas` VALUES (24,'Quimioterapia');
INSERT INTO `sintomas` VALUES (25,'Resfrios persistentes');
INSERT INTO `sintomas` VALUES (26,'Tratamiento con cortisona');
INSERT INTO `sintomas` VALUES (27,'Tuberculosis');
INSERT INTO `sintomas` VALUES (28,'Ulceras');
INSERT INTO `sintomas` VALUES (29,'Valvulas artificiales');
INSERT INTO `sintomas` VALUES (30,'Rubeola');
INSERT INTO `sintomas` VALUES (31,'Fiebre reumatica');
INSERT INTO `sintomas` VALUES (32,'Otros');